
- name: Update apt cache (for Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present
  become: yes

