
- name: Check if K3s agent is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s 
  register: k3s_agent_binary

- name: Install K3s agent on data plane nodes
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[groups['control_plane'][0]]['k3s_node_token'] }} sh -"
  args:
    creates: /usr/local/bin/k3s
  become: yes
  when: not k3s_agent_binary.stat.exists

- name: Ensure K3s agent service is started and enabled
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: yes
  become: yes

