---
- name: Add CloudNativePG Helm repository
  kubernetes.core.helm_repository:
    name: cnpg
    repo_url: "https://cloudnative-pg.github.io/charts"
    state: present

- name: Install CloudNativePG operator from Helm chart
  kubernetes.core.helm:
    name: cnpg                     
    chart_ref: cnpg/cloudnative-pg  
    release_namespace: cnpg-system  # Namespace to install the operator into
    create_namespace: yes           
    state: present                  
    
