
- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install K3s on control plane
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    creates: /usr/local/bin/k3s 
  become: yes
  when: not k3s_binary.stat.exists

- name: Ensure K3s service is started and enabled
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: yes
  become: yes

- name: Get K3s node token from control plane
  ansible.builtin.command: "sudo cat /var/lib/rancher/k3s/server/node-token"
  register: k3s_node_token_raw
  changed_when: false
  become: yes

- name: Set K3s node token as a fact
  ansible.builtin.set_fact:
    k3s_node_token: "{{ k3s_node_token_raw.stdout }}"

